image: edgarogh/patatruck-ci

stages:
  - build
  - test

build:
  stage: build
  script:
    - bash -c 'pushd info3.game.given.2021/game/info3/automata/parser/ && javacc -STATIC=false parser_automata.jj && popd'
    - bash -O globstar -c 'javac info3.game.given.2021/**/*.java'

lint:
  stage: test
  script:
    - bash -O globstar -c 'checkstyle -c patatruck_checkstyle.xml info3.game.given.2021/graphics/**/Awt*.java info3.game.given.2021/game/info3/game/**/*.java'
